/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package done;

import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class Front extends javax.swing.JFrame {

    String[]dataText = new String[]{"Aman","Ajay","Asta","Ratna"};
    
    /**
     * Creates new form Front
     */
    public Front() {
        initComponents();
    }

    
    public static String getTextVector(String data, String[]dataText){
        
        int position = getPositionVectorText(data, dataText);
        if(position==-1){
            return data;
        }
        return dataText[position];
    }
    
    public static void addTextAndSelectTextToReset(JTextField textField, String newData){
        
        String data = "";
        int actualNo = textField.getText().length();
        data = newData.substring(actualNo, newData.length());
        if(newData.isEmpty()||data.isEmpty()){
            return;
        }
        try{
            textField.getDocument().insertString(textField.getCaretPosition(), data, null);
        }catch(Exception e){
            
        }
        textField.select(actualNo, textField.getText().length());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

        if(evt.getKeyCode()>=65&&evt.getKeyCode()<=90 || evt.getKeyCode()>=96&&evt.getKeyCode()<=110 || evt.getKeyCode()==evt.VK_ENTER){
            return;
        }
        if(jTextField1.getText().isEmpty()){
            return;
        }
        if(dataText.length==0)
            return;
        addTextAndSelectTextToReset(jTextField1,getTextVector(jTextField1.getText(), dataText));
        
    }//GEN-LAST:event_jTextField1KeyReleased

    public static int getPositionVectorText(String data, String[]dataText){
        
        try{
            for(int i=0; i<dataText.length; i++){
                
                if(data.equals(dataText[i].substring(0, data.length()))){
                    return i;
                }
                
            }
        }catch(Exception e){
            
        }
        return -1;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Front().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
